### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oxr463** [runlevel5/vagrant-boxes-ppc64le#1]
> Codes are based on:

See: https://github.com/osuosl/packer-templates/blob/master/LICENSE

**Comment by runlevel5** [comment]
@oxr463 sorry what do you mean?

**Comment by oxr463** [comment]
This repository does not contain a license. The one in the Credits section of the README.md file is licensed under the GPL-2.0-only.

**Comment by runlevel5** [comment]
I've added LICENSE file
